version: '3.8'

services:
  swimming-academy-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - DB_PASSWORD=H9My6r3Rfu4tZ$T
      - JWT_KEY=f6f6f6fhshhdavhff6f67sjeiejsmds
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - swimming-academy-network

networks:
  swimming-academy-network:
    driver: bridge 